force-app/main/default/objects/ContractRelationship__c/ContractRelationship__c.object-meta.xml
<CustomObject>
    <label>Contract Relationship</label>
    <nameField>
        <label>Contract Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractRelationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contract Relationships</relationshipLabel>
    <relationshipName>Contract_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractRelationship__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Relationships</relationshipLabel>
    <relationshipName>Contract_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContractRelationship__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Financeiro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractController.cls
public with sharing class ContractController {
  @AuraEnabled(cacheable=true)
  public static List<ContractRelationship__c> getRelatedContacts(
    Id contractId
  ) {
    return [
      SELECT Id, Role__c, Contact__c, Contact__r.Name, Contact__r.Email
      FROM ContractRelationship__c
      WHERE Contract__c = :contractId
    ];
  }

  @AuraEnabled
  public static void updateContactRole(Id relationshipId, String newRole) {
    ContractRelationship__c itemToUpdate = new ContractRelationship__c();
    itemToUpdate.Id = relationshipId;
    itemToUpdate.Role__c = newRole;
    update itemToUpdate;
  }

  @AuraEnabled
  public static void deleteContractRelationship(Id relationshipId) {
    ContractRelationship__c itemToDelete = new ContractRelationship__c();
    itemToDelete.Id = relationshipId;
    delete itemToDelete;
  }
}